### ISSUE TITLE
anim.py (ellipse() got an unexpected keyword argument 'width' )

### ISSUE THREAD

**Issue by CozmoCyke** [zayfod/pycozmo#12]
In a previous dev , it works without error but now it doesn't !
Windows 7

Behaviour seen : Cozmo light its backpack light in green.

D:\dev\Cozmo\pycozmo\20190922\examples>python anim.py
2019-09-23 00:48:17.195 pycozmo.general      INFO     Firmware version 2381.
2019-09-23 00:48:17.226 pycozmo.general      INFO     Body S/N 0x45a0330c.
Traceback (most recent call last):
  File "anim.py", line 13, in <module>
    pycozmo.run_program(pycozmo_program)
  File "C:\Python35\lib\site-packages\pycozmo-0.5.0-py3.5.egg\pycozmo\run.py", l
ine 44, in run_program
    f(cli)
  File "anim.py", line 8, in pycozmo_program
    clips = pycozmo.anim.load_anim_clips(fspec)
  File "C:\Python35\lib\site-packages\pycozmo-0.5.0-py3.5.egg\pycozmo\anim.py",
line 266, in load_anim_clips
    clip = load_anim_clip(fbclips.Clips(i))
  File "C:\Python35\lib\site-packages\pycozmo-0.5.0-py3.5.egg\pycozmo\anim.py",
line 232, in load_anim_clip
    render_face(face)
  File "C:\Python35\lib\site-packages\pycozmo-0.5.0-py3.5.egg\pycozmo\anim.py",
line 113, in render_face
    draw.ellipse(xy=((x1, y1), (x2, y2)), fill=1, outline=1, width=1)
TypeError: ellipse() got an unexpected keyword argument 'width'

**Comment by zayfod** [comment]
OK, The `width` attribute was added to `ImageDraw.ellipse()` in version 6.0.0, so I clarified the requirements with #eb58b590 . Thanks.
